#!/usr/bin/env bash
#This will redirect permanently
sudo apt -y update
sudo apt -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "30 i\ \tlocation /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx start
