#!/usr/bin/env bash
#This will redirect permanently
sudo apt -y update
sudo apt -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx start
