#!/usr/bin/env bash
#Installing load balancer
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend localnodes
    bind *:80
    mode http
    default_backend nodes

    backend nodes
    mode http
    balance roundrobin
    server 1160-web-01 3.84.104.13:80
    server 1160-web-02 35.237.21.147:80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart