#!/usr/bin/env bash
# This will create a fizz buzz
x="1"
while [ $x -le 100 ]
do
	if [ $((x%3)) -eq 0 ] && [ $((x%5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((x%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$x"
	fi
x=$((++x))
done
