#!/usr/bin/env bash
# This will create bad and good luck
x="1";
while [ $x -lt 10 ];
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi	
x=$(( x + 1 ))
done
